"""Application entry points."""

from __future__ import annotations

from pathlib import Path

from .html_build import build_html
from .parse import extract_title


def run(path: Path) -> str:
    """Process the provided HTML file and return simple HTML.

    Parameters
    ----------
    path:
        Path to a HTML file to be processed.
    """
    html = Path(path).read_text(encoding="utf-8")
    title = extract_title(html)
    return build_html(title, "Generated by lectio_plus")
