name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -U pip
      - run: python -m pip install -r requirements.txt
      - run: python -m ruff check .
      - run: python -m mypy src
      - run: python -m pytest -q
